[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "openhands_dynamic_agent_factory"
version = "0.1.6"
authors = [
  { name="OpenHands", email="openhands@all-hands.dev" },
]
description = "Dynamic agent factory for OpenHands that generates micro-agents based on technology keywords"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "openhands>=0.1.0",
    "dataclasses;python_version<'3.7'"
]

[project.optional-dependencies]
python = ["ast", "pylint"]
react = ["esprima", "eslint"]
node = ["acorn", "eslint"]
sql = ["sqlparse", "sqlalchemy"]
all = [
    "ast",
    "pylint",
    "esprima",
    "eslint",
    "acorn",
    "sqlparse",
    "sqlalchemy"
]

[project.urls]
"Homepage" = "https://github.com/makafeli/openhands-dynamic-agent-factor"
"Bug Tracker" = "https://github.com/makafeli/openhands-dynamic-agent-factor/issues"