name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov mypy black isort
        pip install -e .

    - name: Install Node.js dependencies
      run: |
        npm ci
        npm install -g typescript jest

    - name: Run Python tests
      run: |
        pytest --cov=openhands_dynamic_agent_factory tests/
        black --check openhands_dynamic_agent_factory
        isort --check-only openhands_dynamic_agent_factory
        mypy openhands_dynamic_agent_factory

    - name: Run Node.js tests
      run: |
        npm run test
        npm run lint
        npm run type-check

    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
