name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          npm ci
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update npm dependencies
        run: |
          npm outdated || true
          npm update
          npm audit fix || true

      - name: Update Python dependencies
        run: |
          pip list --outdated
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt --upgrade || true
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update dependencies"
          title: "chore(deps): update dependencies"
          body: |
            This PR updates project dependencies to their latest versions.
            
            Changes:
            - Updates npm packages
            - Updates Python packages
            
            Please review the changes and merge if everything looks good.
          branch: "deps/update-dependencies"
          base: "main"
          labels: "dependencies"
